# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
#
# See https://cloud.vespa.ai/en/automated-deployments for details.

name: Deploy vector-search to Vespa Cloud
on:
  push:
    branches: [ main ]
  schedule:
    # 5:40 UTC daily 
    - cron: '40 5 * * *'

# See https://cloud.vespa.ai/en/security/guide#application-key for how to generate a control-plane key:
#
#   vespa auth api-key -a vespa-team.vector-search.default
#
# Then use key in ~/.vespa/vespa-team.api-key.pem, add its content into a GitHub Secret.
env:
  VESPA_CLI_API_KEY: ${{ secrets.VESPA_TEAM_VESPACLOUD_VECTOR_SEARCH_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Get latest Vespa CLI
      working-directory: .
      run: |
        apt update && apt -y install curl
        mkdir -p opt
        VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")')
        curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | \
          tar -zxf - -C opt
        ln -fs ./opt/*/bin/vespa

    - name: Deploy to Vespa Cloud
      working-directory: .
      run: |
        ./vespa config set target cloud
        ./vespa config set application vespa-team.vector-search
        ./vespa prod deploy \
          --source-url "$(git config --get remote.origin.url | sed 's+git@\(.*\):\(.*\)\.git+https://\1/\2+')/commit/$(git rev-parse HEAD)"
